-- Run after 001_products.sql in Supabase SQL Editor or via supabase db reset
truncate table public.products restart identity cascade;

insert into public.products (
  sku, name, slug, description, brand, price, compare_at_price, images, specs,
  occasions, recipients, collections, tags, in_stock
) values
(
  'KAY-TF-001',
  'Tom Ford Black Orchid',
  'tom-ford-black-orchid',
  'An opulent floral fragrance presented in Kay signature packaging — a timeless gift for her.',
  'Tom Ford',
  185000,
  null,
  array['https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&h=900&fit=crop'],
  '{"Notes":"Black orchid, plum, spices","Volume":"50ml","Packaging":"Kay luxury box"}'::jsonb,
  array['birthday', 'anniversary'],
  array['for-her'],
  array['luxury'],
  array['bestseller'],
  true
),
(
  'KAY-TRV-002',
  'Luxury Travel Gift Set',
  'luxury-travel-gift-set',
  'Curated travel essentials in a leather-style case — perfect for the frequent flyer.',
  'Kay Stores',
  95000,
  110000,
  array['https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&h=900&fit=crop'],
  '{"Contents":"Eye mask, passport holder, mini fragrance","Material":"Vegan leather"}'::jsonb,
  array['birthday', 'thank-you'],
  array['for-him', 'for-friends'],
  array['luxury'],
  array['new'],
  true
),
(
  'KAY-HMP-003',
  'Kay Signature Hamper',
  'kay-signature-hamper',
  'Our flagship hamper with artisan treats, fine teas, and handcrafted chocolates.',
  'Kay Stores',
  150000,
  null,
  array['https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=800&h=900&fit=crop'],
  '{"Items":"12 curated pieces","Shelf life":"6 months","Gift wrap":"Included"}'::jsonb,
  array['anniversary', 'thank-you', 'wedding'],
  array['for-her', 'for-him', 'for-parents', 'for-friends'],
  array['luxury'],
  array['bestseller'],
  true
),
(
  'KAY-NCK-004',
  'Baublebar Initial Necklace',
  'baublebar-initial-necklace',
  'Personalised gold-tone initial pendant on a delicate chain.',
  'Baublebar',
  55000,
  null,
  array['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&h=900&fit=crop'],
  '{"Material":"Gold-plated brass","Chain length":"18 inches","Personalisation":"Single initial"}'::jsonb,
  array['birthday', 'graduation'],
  array['for-her', 'for-friends'],
  array['luxury'],
  array['new'],
  true
),
(
  'KAY-CND-005',
  'Premium Scented Candle Set',
  'premium-scented-candle-set',
  'A trio of hand-poured soy candles in velvet, amber, and white tea.',
  'Kay Stores',
  42000,
  null,
  array['https://images.unsplash.com/photo-1602607894039-8a177834a14c?w=800&h=900&fit=crop'],
  '{"Burn time":"45 hours each","Wax":"Natural soy","Set size":"3 candles"}'::jsonb,
  array['birthday', 'thank-you', 'new-baby'],
  array['for-her', 'for-friends', 'for-parents'],
  array['luxury'],
  array[]::text[],
  true
),
(
  'KAY-WCH-006',
  'Minimalist Swiss Watch',
  'minimalist-swiss-watch',
  'Slim-profile timepiece with sapphire crystal — understated elegance for him.',
  'Kay Stores',
  320000,
  null,
  array['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&h=900&fit=crop'],
  '{"Movement":"Quartz","Case":"40mm stainless steel","Water resistance":"50m"}'::jsonb,
  array['birthday', 'anniversary', 'graduation'],
  array['for-him'],
  array['luxury'],
  array['exclusive', 'night_collection'],
  true
),
(
  'KAY-SKN-007',
  'La Mer Skincare Ritual Set',
  'la-mer-skincare-ritual-set',
  'A luxurious skincare ritual featuring cult-favourite moisturising cream.',
  'La Mer',
  275000,
  null,
  array['https://images.unsplash.com/photo-1570194063590-9a05911a2c2b?w=800&h=900&fit=crop'],
  '{"Contents":"Cream, serum, eye treatment","Skin type":"All"}'::jsonb,
  array['birthday', 'anniversary'],
  array['for-her', 'for-parents'],
  array['luxury'],
  array['exclusive'],
  true
),
(
  'KAY-WHS-008',
  'Single Malt Whisky Collection',
  'single-malt-whisky-collection',
  'Three premium single malts in a wooden presentation case.',
  'Kay Stores',
  198000,
  225000,
  array['https://images.unsplash.com/photo-1569529465841-df988a02da7a?w=800&h=900&fit=crop'],
  '{"Volume":"3 x 200ml","Age":"12–18 years","Presentation":"Walnut case"}'::jsonb,
  array['birthday', 'thank-you'],
  array['for-him', 'for-friends'],
  array['luxury'],
  array['night_collection'],
  true
),
(
  'KAY-BBY-009',
  'Organic Baby Welcome Box',
  'organic-baby-welcome-box',
  'Soft organic blankets, muslin, and keepsake items for new parents.',
  'Kay Stores',
  68000,
  null,
  array['https://images.unsplash.com/photo-1515488042361-ee00e17ddd4f?w=800&h=900&fit=crop'],
  '{"Material":"Organic cotton","Age":"0–12 months","Items":"8 pieces"}'::jsonb,
  array['new-baby', 'thank-you'],
  array['for-kids', 'for-parents', 'for-friends'],
  array['luxury'],
  array['new'],
  true
),
(
  'KAY-PLT-010',
  'Executive Leather Portfolio',
  'executive-leather-portfolio',
  'Hand-stitched portfolio with monogram option — ideal for corporate gifting.',
  'Kay Stores',
  125000,
  null,
  array['https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&h=900&fit=crop'],
  '{"Material":"Full-grain leather","Monogram":"Up to 3 initials","Fits":"A4 documents"}'::jsonb,
  array['thank-you', 'graduation'],
  array['for-him'],
  array['corporate', 'luxury'],
  array['bestseller'],
  true
),
(
  'KAY-CRP-011',
  'Corporate Gift Hamper — Classic',
  'corporate-gift-hamper-classic',
  'Premium hamper designed for client appreciation and team milestones.',
  'Kay Stores',
  89000,
  null,
  array['https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=800&h=900&fit=crop'],
  '{"Bulk orders":"10+ units","Branding":"Custom card available","Delivery":"Nationwide"}'::jsonb,
  array['thank-you'],
  array['corporate-gifts'],
  array['corporate'],
  array[]::text[],
  true
),
(
  'KAY-CRP-012',
  'Corporate Desk Essentials Set',
  'corporate-desk-essentials-set',
  'Marble desk tray, pen, and notebook set for the modern executive.',
  'Kay Stores',
  72000,
  null,
  array['https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&h=900&fit=crop'],
  '{"Material":"Marble and brass","Items":"4 pieces","Gift wrap":"Included"}'::jsonb,
  array['thank-you', 'graduation'],
  array['corporate-gifts', 'for-him'],
  array['corporate'],
  array[]::text[],
  true
),
(
  'KAY-CHK-013',
  'Artisan Chocolate Collection',
  'artisan-chocolate-collection',
  'Single-origin chocolates from master chocolatiers worldwide.',
  'Kay Stores',
  38000,
  null,
  array['https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=800&h=900&fit=crop'],
  '{"Pieces":"24","Storage":"Cool dry place","Allergens":"Contains dairy, nuts"}'::jsonb,
  array['birthday', 'thank-you', 'wedding'],
  array['for-her', 'for-him', 'for-friends', 'for-parents'],
  array['luxury'],
  array[]::text[],
  true
),
(
  'KAY-FLW-014',
  'Forever Rose in Glass Dome',
  'forever-rose-glass-dome',
  'Preserved rose under a glass cloche — romance that lasts.',
  'Kay Stores',
  48000,
  null,
  array['https://images.unsplash.com/photo-1490750967868-88aa4486cfe2?w=800&h=900&fit=crop'],
  '{"Lifespan":"Up to 3 years","Colour":"Deep red","Base":"Black lacquer"}'::jsonb,
  array['anniversary', 'wedding', 'birthday'],
  array['for-her'],
  array['luxury'],
  array['bestseller'],
  true
),
(
  'KAY-TEA-015',
  'Japanese Tea Ceremony Set',
  'japanese-tea-ceremony-set',
  'Ceramic teapot, cups, and premium sencha for mindful moments.',
  'Kay Stores',
  62000,
  null,
  array['https://images.unsplash.com/photo-1564890369478-c89ca6d13667?w=800&h=900&fit=crop'],
  '{"Origin":"Kyoto blend","Set":"Pot + 4 cups","Care":"Hand wash only"}'::jsonb,
  array['thank-you', 'birthday'],
  array['for-parents', 'for-friends'],
  array['luxury'],
  array[]::text[],
  true
),
(
  'KAY-TOY-016',
  'Heirloom Wooden Toy Set',
  'heirloom-wooden-toy-set',
  'Handcrafted wooden blocks and animals in a keepsake chest.',
  'Kay Stores',
  45000,
  null,
  array['https://images.unsplash.com/photo-1558060370-0466aea824a6?w=800&h=900&fit=crop'],
  '{"Material":"FSC beechwood","Age":"3+","Finish":"Non-toxic paint"}'::jsonb,
  array['birthday', 'new-baby'],
  array['for-kids'],
  array['luxury'],
  array['new'],
  true
),
(
  'KAY-PNR-017',
  'Gallery-Quality Art Print',
  'gallery-quality-art-print',
  'Limited edition print by a contemporary African artist, framed.',
  'Kay Stores',
  88000,
  null,
  array['https://images.unsplash.com/photo-1579783902614-fd0a3a7eb2a8?w=800&h=900&fit=crop'],
  '{"Edition":"Limited 100","Frame":"Oak","Size":"24 x 36 inches"}'::jsonb,
  array['anniversary', 'graduation', 'thank-you'],
  array['for-friends', 'for-parents', 'for-him', 'for-her'],
  array['luxury'],
  array['exclusive'],
  true
),
(
  'KAY-SPA-018',
  'Couples Spa Experience Voucher',
  'couples-spa-experience-voucher',
  'A full-day spa retreat for two at a partner wellness sanctuary.',
  'Kay Stores',
  165000,
  null,
  array['https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&h=900&fit=crop'],
  '{"Duration":"6 hours","Includes":"Massage, lunch, pool access","Validity":"12 months"}'::jsonb,
  array['anniversary', 'wedding', 'birthday'],
  array['for-her', 'for-him', 'for-friends'],
  array['luxury'],
  array['night_collection'],
  true
),
(
  'KAY-WED-019',
  'Wedding Keepsake Box',
  'wedding-keepsake-box',
  'Engraved memory box for vows, rings, and treasured mementos.',
  'Kay Stores',
  92000,
  null,
  array['https://images.unsplash.com/photo-1519741497674-611481863552?w=800&h=900&fit=crop'],
  '{"Material":"Walnut wood","Engraving":"Names + date","Lining":"Ivory suede"}'::jsonb,
  array['wedding', 'anniversary'],
  array['for-her', 'for-him', 'for-friends'],
  array['luxury'],
  array[]::text[],
  true
),
(
  'KAY-GRD-020',
  'Graduation Success Gift Set',
  'graduation-success-gift-set',
  'Pen, journal, and motivational keepsake for the new graduate.',
  'Kay Stores',
  58000,
  null,
  array['https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=900&fit=crop'],
  '{"Items":"5 pieces","Journal":"192 pages","Packaging":"Kay gift box"}'::jsonb,
  array['graduation', 'birthday'],
  array['for-him', 'for-her', 'for-friends', 'for-kids'],
  array['luxury', 'corporate'],
  array['new'],
  true
);
