insert into public.products (
  sku, name, slug, description, brand, price, compare_at_price, images, specs,
  occasions, recipients, collections, tags, in_stock, stock_quantity,
  vendor_id, status, segment
) values
(
  'TEST-KAY-001',
  'Kay Test Perfume Set',
  'kay-test-perfume-set',
  'Test product for checkout and Kay Reveal — floral fragrance duo in signature packaging.',
  'Kay Stores',
  75000,
  null,
  array['https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&h=900&fit=crop'],
  '{"Volume":"2 x 30ml","Packaging":"Kay gift box","Purpose":"QA seed"}'::jsonb,
  array['birthday', 'anniversary'],
  array['for-her'],
  array['luxury'],
  array['bestseller', 'test'],
  true,
  50,
  '69230075-f5e3-4014-bea5-8bc5252bd3fd',
  'live',
  'gifting'
),
(
  'TEST-KAY-002',
  'Kay Test Leather Wallet',
  'kay-test-leather-wallet',
  'Test product for him — slim wallet for gift flow and order testing.',
  'Kay Stores',
  55000,
  65000,
  array['https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&h=900&fit=crop'],
  '{"Material":"Vegan leather","Color":"Black","Purpose":"QA seed"}'::jsonb,
  array['birthday', 'thank-you'],
  array['for-him'],
  array['luxury'],
  array['new', 'test'],
  true,
  50,
  '69230075-f5e3-4014-bea5-8bc5252bd3fd',
  'live',
  'gifting'
),
(
  'TEST-KAY-003',
  'Kay Test Candle Trio',
  'kay-test-candle-trio',
  'Test home gift — three scented candles for MOV / cart testing.',
  'Kay Stores',
  48000,
  null,
  array['https://images.unsplash.com/photo-1602607894039-8a177834a14c?w=800&h=900&fit=crop'],
  '{"Set":"3 candles","Burn time":"40h each","Purpose":"QA seed"}'::jsonb,
  array['thank-you', 'housewarming'],
  array['for-her', 'for-friends'],
  array['luxury'],
  array['test'],
  true,
  50,
  '69230075-f5e3-4014-bea5-8bc5252bd3fd',
  'live',
  'gifting'
),
(
  'TEST-KAY-200',
  'Kay Paystack Test Item',
  'kay-paystack-test-item',
  '₦200 QA item for live Paystack checkout testing. Enable NEXT_PUBLIC_KAY_TEST_CHECKOUT=1 locally so MOV and fees are waived.',
  'Kay Stores',
  200,
  null,
  array['https://images.unsplash.com/photo-1513885535751-8b9238bd345a?w=800&h=900&fit=crop'],
  '{"Purpose":"Paystack QA","Amount":"200 NGN"}'::jsonb,
  array['thank-you'],
  array['for-friends'],
  array['luxury'],
  array['test', 'paystack'],
  true,
  100,
  '69230075-f5e3-4014-bea5-8bc5252bd3fd',
  'live',
  'gifting'
)
on conflict (sku) do update set
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  in_stock = true,
  stock_quantity = excluded.stock_quantity,
  status = 'live',
  segment = 'gifting';
